### ISSUE TITLE
求教如何改变headerHeight的高度值以及菜单布局疑惑

### ISSUE THREAD

**Issue by cc001** [tianzhuo112/VTMagic#1]
现在我看高度是在初始化中写死的64， headerHeight属性暴露出来了，但是赋值好像没用～～～～

 大致五六个选项时候 用默认的选项布局时候4s是正常的，6plus的选项菜单如果没占满屏宽的时候会整体偏左，没有居中；用等分的布局模式6plus的显示可以正常，但是4s的屏宽不够会导致按钮中的部分字显示不完全，会省略掉一部分～

**Comment by tianzhuo112** [comment]
你好！关于第一个问题，你可以把headerView的backgroundColor设为redColor，然后再调试一下试试；第二个问题，针对你这种情况，一种解决方案是4s采用默认布局，其它设备用等分布局。4s的屏幕太窄，完整显示五六个比较困难，除非把字体调到足够小，但这样的体验目测不是太好。

**Comment by cc001** [comment]
谢～ 第一个问题我把naviView 和 headerView弄混了～
