### ISSUE TITLE
关于子控制器View的预览问题

### ISSUE THREAD

**Issue by VVJason** [tianzhuo112/VTMagic#10]
默认是会预览控制器View的，可以增加关闭选项吗？现在默认进去后第一个和第二个控制器的view都加载完毕了。
![snip20160617_51](https://cloud.githubusercontent.com/assets/14148888/16146146/302295ce-34af-11e6-8d50-7f1134a90d54.png)

**Comment by tianzhuo112** [comment]
你好，为了保证切换的流畅性，默认会预加载下一个页面，通常我们会在viewDidLoad中完成一些基础配置（如初始化子视图等），仅当viewDidAppear:方法触发时，页面才真正显示，你或许还需要与viewWillDisappear:等方法配合使用，建议将页面数据的请求和加载在这些方法中，当然你也可以在页面的menu信息改变时完成这些操作。后续我会增加一些类似的事例，以供大家参考。

**Comment by VVJason** [comment]
道理是这样的啊，但是还是建议增加这个配置啊，还有就是VTMagicViewDelegate里面有viewDidAppeare等方法，有可能增加viewWillAppeare等这些will的方法吗？

**Comment by tianzhuo112** [comment]
如果去掉预加载逻辑，用户在滑动切换的时候可能会有瞬间的卡顿和不自然。另外，在去掉预加载的情况下，如何保证用户切换的流畅又将是另外一个“预加载”问题，事实上在页面可重用的情况下，预加载下一个页面的内存开销是极小的。关于VTMagicViewDelegate中新增viewWillAppeare等方法是一个很好的建议，我会认真考虑，在确保测试无误的情况下，该特性会在未来的版本中得到体现。最后，非常感谢你的反馈和建议，祝周末愉快！

**Comment by VVJason** [comment]
我们页面是固定几个的，没有可以重用的情况，，所以感觉预加载也是有点奇怪

**Comment by tianzhuo112** [comment]
嗯，原来如此～！[握手]

**Comment by tianzhuo112** [comment]
你好，最新版1.2.3已新增预加载开关，将属性needPreloading置为NO即可关闭预加载逻辑，如有问题请及时反馈！

**Comment by VVJason** [comment]
needPreloading设为NO后切换动画没有了😳

**Comment by tianzhuo112** [comment]
你好，因为没有预加载下一页，如果显示动画的话，中间会有一段空白，用户体验不是特别好，鱼与熊掌难以兼得！！

**Comment by VVJason** [comment]
但是对于固定的几页内容，虽然没有预加载，但是在左右滑动的时候控制器的View已经加载过了，这种情况是可以有动画。你可以判断isViewLoaded判断一下view是否加载过，加载过有动画没有加载就没有动画。

**Comment by tianzhuo112** [comment]
事情并没有想象中那么简单，如果不把控制器加载出来，就不知道下一个控制器会是哪一个，而如果要加载控制器，势必又要想办法区分其需不需要触发生命周期方法，这样的结果只会让框架变得更加复杂和难以理解。

**Comment by VVJason** [comment]
那就哦了
