### ISSUE TITLE
iphoneX上，旋转屏幕，视图向左右偏移一些距离

### ISSUE THREAD

**Issue by CoderWQ** [tianzhuo112/VTMagic#103]
您好，iPhoneX上，旋转屏幕，从竖屏到横屏，在竖屏，视图会偏移44，模拟器也可以调试。
demo也有问题，求个解决办法。

**Comment by wukaiqiang** [comment]
_contentView = [[VTContentView alloc] init];
找个这个scrollView的初始化 加上
if (@available(iOS 11.0, *)) {
            _contentView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        }
ios11适配
