### ISSUE TITLE
从详情页面返回列表页面, 重新刷新 tableView, cell 有时候会出现自动上移的跳动.

### ISSUE THREAD

**Issue by CXTretar** [tianzhuo112/VTMagic#108]

**Comment by Suzhibin** [comment]
这好像和 这个框架没关系  你刷新的是用什么 MJ 吗？

**Comment by CXTretar** [comment]
@Suzhibin 我直接在demo中做的测试, 你可以 在` VTRecomViewController.h`中添加刷新代码测试
```
 - (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    self.tableView.scrollsToTop = YES;
    
    [self fetchNewsData];
    [self.tableView reloadData];
    
    VTPRINT_METHOD
}

```
尤其是在一个cell 靠近tableView 顶部即将消失时去做点击, 他会自动上移.

**Comment by Suzhibin** [comment]
@CXTretar  
加上 这个试试
 if (@available(iOS 11.0,*))  {
        tableView.estimatedRowHeight = 0;
        tableView.estimatedSectionFooterHeight = 0;
        tableView.estimatedSectionHeaderHeight = 0;
    }

**Comment by CXTretar** [comment]
@Suzhibin self.tableView.estimatedRowHeight = 0;假如设置这一项就不会出现, 实际项目中由于采用的是自动计算高度, 所以self.tableView.estimatedRowHeight 是有值的, 有其他解决方案么.

**Comment by Suzhibin** [comment]
@CXTretar  这是初始化的时候设置的   ，自动计算高度可以在代理中写。

**Comment by CXTretar** [comment]
@Suzhibin 我用的是tableViewCell 自动布局, tableView 设置了estimatedRowHeight之后就可以自动计算了, 不过改成固定行高也是可以的.

**Comment by CXTretar** [comment]
@Suzhibin 我通过自己缓存行高, 已经实现了,谢谢.
