### ISSUE TITLE
iPhone X leftNavigatoinItem and rightNavigatoinItem

### ISSUE THREAD

**Issue by bignuctsl** [tianzhuo112/VTMagic#117]
![1536922925168](https://user-images.githubusercontent.com/7566562/45546721-b77b3680-b850-11e8-88d8-982059008f80.jpg)

**Comment by Suzhibin** [comment]
self.magicView.againstStatusBar = NO;  设置这个试试

**Comment by bignuctsl** [comment]
设置了就这样
<img width="411" alt="wx20180921-111933 2x" src="https://user-images.githubusercontent.com/7566562/45858496-5e4f5d80-bd90-11e8-8410-731e71a881e1.png">
这样就得设置 self.magicView.navigationHeight = 44;然后会
<img width="386" alt="wx20180921-111853 2x" src="https://user-images.githubusercontent.com/7566562/45858647-006f4580-bd91-11e8-9e7c-c3a1915dbbf9.png">

整个的用法是
_magicController = [[VTMagicController alloc] init];
        _magicController.magicView.navigationColor = [UIColor whiteColor];
        _magicController.magicView.sliderColor = [UIColor blackColor];
        _magicController.magicView.layoutStyle = VTLayoutStyleCenter;
        _magicController.magicView.switchStyle = VTSwitchStyleDefault;
        _magicController.magicView.againstStatusBar = YES;
        _magicController.magicView.dataSource = self;
        _magicController.magicView.delegate = self;
        _magicController.magicView.leftNavigatoinItem = self.leftButton;
        _magicController.magicView.rightNavigatoinItem = self.rightButton;

**Comment by Suzhibin** [comment]
这个应该 作者适配iPhone X 忘记rightNavigatoinItem 按钮的Y 了   。 只能改源码了 在VTmagicView.m 里的updateFrameForRightNavigationItem 方法内  你调一下rightFrame.origin.y 的值

**Comment by Suzhibin** [comment]
- (void)updateFrameForRightNavigationItem {
    CGRect rightFrame = _rightNavigatoinItem.bounds;
    CGFloat offset = CGRectGetHeight(rightFrame)/2;
    rightFrame.origin.x = _navigationView.frame.size.width - rightFrame.size.width;
    rightFrame.origin.y = CGRectGetMidY(_navigationView.bounds) - offset;
    
    CGFloat tempY;
    if (KiPhoneX) {
        tempY=20;
    }else{
        tempY=10;
    }
    if (_againstStatusBar && _headerHidden) rightFrame.origin.y += tempY;
    _rightNavigatoinItem.frame = rightFrame;
}
我调试下  应该没问题

**Comment by bignuctsl** [comment]
> * (void)updateFrameForRightNavigationItem {
>   CGRect rightFrame = _rightNavigatoinItem.bounds;
>   CGFloat offset = CGRectGetHeight(rightFrame)/2;
>   rightFrame.origin.x = _navigationView.frame.size.width - rightFrame.size.width;
>   rightFrame.origin.y = CGRectGetMidY(_navigationView.bounds) - offset;
>   CGFloat tempY;
>   if (KiPhoneX) {
>   tempY=20;
>   }else{
>   tempY=10;
>   }
>   if (_againstStatusBar && _headerHidden) rightFrame.origin.y += tempY;
>   _rightNavigatoinItem.frame = rightFrame;
>   }
>   我调试下  应该没问题

谢谢！
- (void)updateFrameForLeftNavigationItem {
    CGRect leftFrame = _leftNavigatoinItem.bounds;
    CGRect statusFrame = [[UIApplication sharedApplication] statusBarFrame];
    CGFloat offset = CGRectGetHeight(leftFrame)/2;
    leftFrame.origin.y = CGRectGetMidY(_navigationView.bounds) - offset;
    if (_againstStatusBar && _headerHidden) leftFrame.origin.y += CGRectGetHeight(statusFrame)/2;
    _leftNavigatoinItem.frame = leftFrame;
}

- (void)updateFrameForRightNavigationItem {
    CGRect rightFrame = _rightNavigatoinItem.bounds;
    CGRect statusFrame = [[UIApplication sharedApplication] statusBarFrame];
    CGFloat offset = CGRectGetHeight(rightFrame)/2;
    rightFrame.origin.x = _navigationView.frame.size.width - rightFrame.size.width;
    rightFrame.origin.y = CGRectGetMidY(_navigationView.bounds) - offset;
    if (_againstStatusBar && _headerHidden) rightFrame.origin.y += CGRectGetHeight(statusFrame)/2;
    _rightNavigatoinItem.frame = rightFrame;
}
我最终这个改了改

**Comment by Suzhibin** [comment]
👍
