### ISSUE TITLE
内存在加载中有点高！

### ISSUE THREAD

**Issue by 977616908** [tianzhuo112/VTMagic#12]
6个item的滑动。内存300M，会提示
2016-06-20 00:04:54.840 TestApp[4903:1922472] Received memory warning.

//我的tableview已经优化了的。

**Comment by tianzhuo112** [comment]
你好，请问页面是否有重用的情况，也就是说是否有调用方法dequeueReusablePageWithIdentifier:？请确保页面的初始化符合demo中的规范，我们公司项目中有多重VTMagic嵌套，设计更加复杂，仍能很好地控制内存，或者你可以用instruments跟踪一下内存开销出在哪个地方。此外，在有大量数据的情况下，我们应该尽可能从数据库中读取缓存数据（比如页面重用时），而不是直接全部保存到内存中。

**Comment by 977616908** [comment]
您好，谢谢您的回复。dequeueReusablePageWithIdentifier用了。框架中一进入就加载了所有页面的数据，VTMagic是否有方法控制滑动后再加载，滑到的页面呢

**Comment by tianzhuo112** [comment]
你好，子控制器中的viewDidAppear:等方法对你应该有用，其调用逻辑与系统一致，viewDidAppear:在页面真正显示时触发，viewWillDisappear:在页面即将消失时触发，另外两个方法可依此类推。此外，vtm_prepareForReuse方法会在页面被重用时触发，你或许需要在这里修正一下页面偏移或者清除一下旧数据。

**Comment by 977616908** [comment]
好的，再次感谢！找到原因了，不知道是不是本质原因。API接口返回了3图的cell时，每张gif图片的大小都在2M中，当我把图片改为100k内，内存突然降到24M中。cell上传的图片对加载和读取，这么占用内存啊？

**Comment by tianzhuo112** [comment]
gif图通常由多张图片合成，所以占用内存一般会比较大-_-!!
