### ISSUE TITLE
设置默认显示的页面

### ISSUE THREAD

**Issue by iphone5s** [tianzhuo112/VTMagic#14]
这个能不能设置默认显示到 第几页。
 我现在是通过switchToPage  切换到想要默认显示的页面，  但是第一页的数据已经被加载了。

**Comment by iphone5s** [comment]
能否留个 qq  或者加我qq  453742103   这里有好几个bug  要给你说一下。

**Comment by tianzhuo112** [comment]
你好，这是一个很好的建议，如果顺利下一版会增加这个feature，717510977。

**Comment by tianzhuo112** [comment]
1.2.2中已新增方法reloadDataToPage:，刷新时传入指定页面即可。
