### ISSUE TITLE
提供是否预加载下一个页面的开关

### ISSUE THREAD

**Issue by peanutgao** [tianzhuo112/VTMagic#15]
麻烦作者提供下是否预加载下一个页面的开关,或者取出预加载的功能.
有些页面用户在使用的时候可能不会去点击, 所有点击都预加载下一个页面,没有太多必要,会浪费用户流量.也会增加接口服务器的负担.

**Comment by tianzhuo112** [comment]
你好，关于这点，你可以考虑将网络请求放在viewDidAppear:方法中，该方法会在页面真正显示时触发，这样就避免了不需要的流量开销和服务器负担，作为必要的补充，你或许需要判断一下当前是否需要已经加载过数据。

**Comment by tianzhuo112** [comment]
你好，我想了解一下，你们的页面支持滑动切换吗？这有助于我评估该逻辑的必要性。

**Comment by lynnleelhl** [comment]
我也遇到了同样的问题，希望能够提供一个是否预加载的选项。加载请求写在viewDidAppear不是不可以，只是大家通常习惯写在viewDidLoad里面，从使用便利的角度考虑，我认为这个功能还是有必要增加的。

**Comment by lynnleelhl** [comment]
我读了你的源码，我看到你是通过一个叫vtm_isNeedDisplayWithFrame来判断是否显示在屏幕上，如果是则会加载。我的想法是可以把这个函数改成isNeedLoad，根据用户的动作（点击还是滑动）、切换的方向（向左还是向右）、是否需要预加载的标志等共同决定是否加载，这样只需增加几个变量并修改这个判断函数即可做到，需要的话我也可以提交我修改的代码୧(๑•̀⌄•́๑)૭

**Comment by peanutgao** [comment]
我们项目中是有好几处用到了, 其中多数是需要支持页面切换的

**Comment by tianzhuo112** [comment]
你好，最新版1.2.3已新增预加载开关，将属性needPreloading置为NO即可关闭预加载逻辑，如有问题请及时反馈！
