### ISSUE TITLE
可以成为页面的一部分吗

### ISSUE THREAD

**Issue by hackjie** [tianzhuo112/VTMagic#16]
比如 手机上半部分是播放窗口，但是下面分为 简介、目录、评论三个segment页面，用你这个轮子实现

**Comment by tianzhuo112** [comment]
你好，这是可以的，我们项目中就有大量这样的实现，只需实例化VTMagicController。

**Comment by hackjie** [comment]
谢了！已经引入我们项目，棒棒的

**Comment by tianzhuo112** [comment]
不客气，如有问题欢迎随时反馈！^_^

**Comment by hackjie** [comment]
这个能给顶部导航栏之间加上 title间竖的分割线吗

**Comment by tianzhuo112** [comment]
这种情况你需要自定义menuItem，然后根据需要itemIndex决定是否需要显示分割线。

**Comment by hackjie** [comment]
OK，谢谢
