### ISSUE TITLE
pod 方式集成后，直接导致我项目本身的TabbarController运行闪退

### ISSUE THREAD

**Issue by itdongbaojun** [tianzhuo112/VTMagic#17]
2016-06-27 11:37:18.479 BaoKu[376:99924] -[BKTabBarController vtm_viewDidAppear:]: unrecognized selector sent to instance 0x14780ee00

**Comment by tianzhuo112** [comment]
你好，假如直接拖入工程呢？我最近正在考虑去掉分类的生命周期逻辑，改为内部调用，这两天会修复这个问题。

**Comment by itdongbaojun** [comment]
目前还没尝试直接拖入，还是等待po主修改这块的逻辑吧，runtime这黑科技替换VC的生命周期函数影响范围有点大，导致我自己的类的生命周期函数也全部都runtime替换了。感谢po主回复的这么快，哈哈。

**Comment by tianzhuo112** [comment]
嗯，runtime影响确实不少，原有设计是为了方便直接使用VTMagicView，开发者自定义自己的magicController，后来一想其实没必要，直接使用VTMagicController更好。这次调整同时也包括默认显示页等逻辑。

**Comment by tianzhuo112** [comment]
同学你好，该问题已在1.2.2中修复，望知晓！

**Comment by itdongbaojun** [comment]
好的，thks。
