### ISSUE TITLE
我想问一下怎么设置magicView的frame

### ISSUE THREAD

**Issue by Mingmingmew** [tianzhuo112/VTMagic#18]
我想问一下怎么设置magicView的frame .h里好像没有类似的接口或者属性可以设置啊，如果我从别的界面push到这个magicview 那么上一个界面的导航栏就把magic上面的nav给遮住了。。。。

**Comment by tianzhuo112** [comment]
你好，正常情况下应该不会出现被遮盖的问题，你可以尝试把demo中的homeNav.navigationBarHidden = YES注释掉看一下效果。至于修改magicView的frame，其实就是修改magicController.view的frame，这和我们平时修改控制器view的frame是一样的逻辑。

**Comment by Mingmingmew** [comment]
不知道为什么我加了这句话就好了 self.magicView.headerHidden = NO;  
不过现在出现了新的问题  我现在VTMagic里面放了4个UIViewController 里面各放着一个tableview 现在是这个情况，我如果按顺序滑动呢 这个4个控制器是可以正常运作的，但是当我直接点击VTMagic上面的按钮进行切换界面的时候，MJRefresh立刻报错了，我打印了一下 每当我点击上面按钮的时候代理方法都会遍历我4个控制器 （不知道是不是这个原因导致）。还有 如果用上面的按钮按顺序按也是不会出现这个错误的 但是如果跳着按就会出现这个错误（例如A直接跳到C）
错误信息如下：
![qq20160701-1](https://cloud.githubusercontent.com/assets/16685324/16515446/a6ac608a-3fa4-11e6-8554-7df1e5178b07.png)
我设置控制器的代码如下：
![qq20160701-0](https://cloud.githubusercontent.com/assets/16685324/16515480/d6e7ca5a-3fa4-11e6-8fa4-c9f6e50e0ccf.png)

**Comment by tianzhuo112** [comment]
你好，这样的写法是有问题的，如果多切换几次，它会重复创建很多个控制器，内存会急剧增加。针对这种情况，你要么将每个页面用一个属性来保存，然后在viewControllerAtPage:直接返回对应的控制器；要么按照demo中的规范先调用dequeueReusablePageWithIdentifier:获取，没有的时候再创建。
