### ISSUE TITLE
涉及到播放器切换全屏怎么控制布局

### ISSUE THREAD

**Issue by hackjie** [tianzhuo112/VTMagic#19]
![image](https://cloud.githubusercontent.com/assets/9956115/16515930/75186dea-3fa7-11e6-87e7-e1e5f591c248.png)
像这个切换全屏时 总是与上面的播放器冲突

**Comment by hackjie** [comment]
不是应该是播放器全屏时 会与下面的magicController冲突

**Comment by tianzhuo112** [comment]
你好，不知道你所说的冲突是指什么冲突？如果是约束冲突，你可以限定magicController的布局，以免播放器全屏的时候，magicController跟着改变。如果是其它冲突，请详细描述一下。

**Comment by hackjie** [comment]
布局冲突，对于segmentController.magicView我可以使用自动布局吗

**Comment by tianzhuo112** [comment]
可以，自动布局是没有问题的！

**Comment by hackjie** [comment]
好的 谢谢！

**Comment by tianzhuo112** [comment]
嗯，不客气！
