### ISSUE TITLE
支持 reloadData

### ISSUE THREAD

**Issue by ryzur-martin** [tianzhuo112/VTMagic#20]
当界面数量发生改变的时候需要 reload

**Comment by tianzhuo112** [comment]
页面数量发生改变的时候手动调用reloadData即可。

**Comment by ryzur-martin** [comment]
哦，原来在 magicView 里，我一直在 vc 里找...

**Comment by tianzhuo112** [comment]
magicController只提供少量方法，所有方法都在magicView.h中。
