### ISSUE TITLE
怎么给导航栏的Item添加小红点 已显示是否有新的消息

### ISSUE THREAD

**Issue by asd8855** [tianzhuo112/VTMagic#21]

**Comment by tianzhuo112** [comment]
关于这点，你需要自定义一个buttom，然后在方法menuItemAtIndex:中根据情况决定是否显示小红点。当菜单栏需要更新时（有新消息时），你可以调用方法reloadMenuTitles刷新，该方法只会更新菜单栏，而不会刷新页面。

**Comment by asd8855** [comment]
不是很会怎么在你的基础上修改

**Comment by tianzhuo112** [comment]
你好，这个就像UITableView的cell一样简单，如下所示，给第二个菜单项增加小圆点，并根据情况决定是否显示。
```objective-c
- (UIButton *)magicView:(VTMagicView *)magicView menuItemAtIndex:(NSUInteger)itemIndex
{
    static NSString *itemIdentifier = @"itemIdentifier";
    VTButton *menuItem = [magicView dequeueReusableItemWithIdentifier:itemIdentifier];
    if (!menuItem) {
        menuItem = [VTButton buttonWithType:UIButtonTypeCustom];
        [menuItem setTitleColor:RGBCOLOR(50, 50, 50) forState:UIControlStateNormal];
        [menuItem setTitleColor:RGBCOLOR(169, 37, 37) forState:UIControlStateSelected];
        menuItem.titleLabel.font = [UIFont fontWithName:@"Helvetica" size:15.f];
    }
    
    menuItem.showDot = NO;
    if (1 == itemIndex) {
        menuItem.showDot = YES; // 根据情况决定是否显示小圆点
    }
    return menuItem;
}
```

**Comment by asd8855** [comment]
我不知道怎么给你现在已有的Button上把小红点添加上

**Comment by asd8855** [comment]
坐标不知道怎么确定

**Comment by asd8855** [comment]
你把你的能给我发下吗  我参考一下

**Comment by tianzhuo112** [comment]
刚刚那些代码是临时写的，至于红色小圆点，你需要在VTButton内部添加一个小圆点视图，并设置好约束或frame，然后根据showDot的值来决定是否显示。

**Comment by asd8855** [comment]
reloadMenuTitles  在哪？

**Comment by asd8855** [comment]
第一次显示是 为什么数据会获取两次才显示界面
[1913:108550] (
    1,
    2,
    3
)
2016-07-07 17:47:22.639[1913:108550] (
    4,
    5,
    6
)

**Comment by tianzhuo112** [comment]
reloadMenuTitles是最新版1.2.3中的方法。。

**Comment by asd8855** [comment]
还有上面那个，数据请求两次才会显示页面。导致第一页也显示的是第二页的数据。但复用的时候有显示正确的数据

**Comment by tianzhuo112** [comment]
关于数据错乱的问题，你需要仔细排查一下，首先确保viewControllerAtPage:中传递的参数没有错误，然后再看下子页面内部的数据请求。

**Comment by asd8855** [comment]
他是首次把你写的loadView方法调了两次才出现的

**Comment by asd8855** [comment]
- (UIViewController *)magicView:(VTMagicView *)magicView viewControllerAtPage:(NSUInteger)pageIndex{
    
此方法在首次加载页面的时候执行了两次

**Comment by tianzhuo112** [comment]
你好，reloadData时viewControllerAtPage:会执行两次，是为了在加载当前页面的同时预加载下一个页面，通过pageIndex我们可以知道当前加载的是第几个页面。只有当viewDidAppear:方法调用时，页面才真正显示。

**Comment by asd8855** [comment]
现在的问题时，viewControllerAtPage执行两次，导致我的第一个页面显示的是第二个页面的数据，第二个页面的数据显示正常，复用的话也是好着的。

**Comment by tianzhuo112** [comment]
那应该是你第一次请求数据的参数传递有问题，你仔细检查一下。。

**Comment by asd8855** [comment]
我用的假数据

**Comment by asd8855** [comment]
小红点那个不能放在menuItemAtIndex 并且不能用ItemIndex判断，他这块是复用的  所以 会导致后面本没有的，应为复用原因也会出现小红点

**Comment by tianzhuo112** [comment]
你好，关于小红点的问题，你需要判断一下，比如ItemIndex为2的时候显示，相反的时候则隐藏。

**Comment by asd8855** [comment]
就是这样写的  但复用的时候 他会从复用层 会把以前有小红点的cell重新拉出来

**Comment by tianzhuo112** [comment]
你好，我大概写了一个简单的实现，请更新项目参见demo中的Detail模块（点击任意cell即可进入详情页）。

**Comment by asd8855** [comment]
大神我发现了一个新的问题，你的最新版本添加关闭预加载功能的入口。当我关闭预加载的时候，当titles滑到最后的时候，从最后向前边滑的时候，title的位置不会自动向前跳。你自己可以把预加载功能关了之后试试。

**Comment by asd8855** [comment]
还有一个就是tabBar会把最后的一行cell遮住部分  ，将magicView的高度减少44就好了。大但我这边一改 每次一更新库，就又要重新改一下。你看你的这边能不能写个入口之类的可以手动设置。求大神帮助

**Comment by tianzhuo112** [comment]
第一个问题，我试了下demo中的几个模块，并没有发现你说的问题，请自行修改一下demo中各模块的needPreloading试一下。至于第二个问题，这是因为系统默认做了延伸处理，把当前控制器的self.edgesForExtendedLayout置为UIRectEdgeNone即可，如同demo中[Center]的处理一样。

**Comment by asd8855** [comment]
第一个问题我是下载你的Demo直接试的，发现的

**Comment by asd8855** [comment]
第二个问题按照你试的还是不行

**Comment by asd8855** [comment]
我查了你说了第二个方法是导航栏的隐藏，我现在是底下的tabBar的遮蔽

**Comment by tianzhuo112** [comment]
你好，首先needPreloading的调整并没有涉及到聚焦逻辑，只是底层页面加载逻辑做了部分修改。至于第二个问题，请将[Center]中的self.edgesForExtendedLayout = UIRectEdgeNone;注释掉，然后滑动到底部查看效果。如仍有问题可以加QQ717510977反馈。

**Comment by asd8855** [comment]
好的
