### ISSUE TITLE
你好，请问下当我的滑动标题只有2个时，怎样让他们居中显示

### ISSUE THREAD

**Issue by 977616908** [tianzhuo112/VTMagic#22]
你好，请问下当我的滑动标题只有2个时，怎样让他们居中显示，VTmagic里面有得设置吗？

**Comment by tianzhuo112** [comment]
你好，请把layoutStyle设为VTLayoutStyleCenter即可，参见demo中[Center]模块。

**Comment by 977616908** [comment]
十分感谢！！~3~
