### ISSUE TITLE
快速滑动vc(选中item在边界处时)时, menuBar会停住，直到你停止才会滑动到对应的item

### ISSUE THREAD

**Issue by xing-ou** [tianzhuo112/VTMagic#27]
快速滑动vc(选中item在边界处时)时, menuBar会停住，直到你停止才会滑动到对应的item，是本来就这么设计的么

**Comment by tianzhuo112** [comment]
你好，这是正常逻辑，避免快速滑动时不必要的性能开销，保证页面切换流畅。
