### ISSUE TITLE
swift使用VTMagic,无法调用setslider和setseperater

### ISSUE THREAD

**Issue by xing-ou** [tianzhuo112/VTMagic#28]
swift使用VTMagic,无法调用setslider和setseperater

**Comment by tianzhuo112** [comment]
你好，我试了下，好像可以～
<img width="780" alt="screen shot 2016-07-24 at 10 25 31 pm" src="https://cloud.githubusercontent.com/assets/17450179/17084535/eb49c2ea-51f2-11e6-9f6a-854115755538.png">

**Comment by junwangInChina** [comment]
你好
我在swift中使用这个库的时候，发现编译不通过。
然后桥接文件中已经把库引入了。
想咨询一下你是怎么使用的。

谢谢！
