### ISSUE TITLE
混编问题

### ISSUE THREAD

**Issue by junwangInChina** [tianzhuo112/VTMagic#29]
你好
我想要在swift工程中使用这个库
pod的是1.2.3版本
在桥接文件中导入了库的头文件
![2016-08-04 17 19 52](https://cloud.githubusercontent.com/assets/2849111/17396817/b45b2670-5a67-11e6-8f83-b1afe449ef89.png)

而在使用时，两种方式都不行
![2016-08-04 17 21 48](https://cloud.githubusercontent.com/assets/2849111/17396881/f7f8010a-5a67-11e6-9741-9bf564a83985.png)
![2016-08-04 17 23 05](https://cloud.githubusercontent.com/assets/2849111/17396909/228d722e-5a68-11e6-92fe-da35b57e8332.png)

然后，我在你们关闭的问题中发现，是有人在swift中使用这个库的，那么是因为版本的问题么？
麻烦有时间帮忙看看。
谢谢！

**Comment by junwangInChina** [comment]
PS：桥接文件是没有问题的，因为引入了其他的OC库，可以正常使用

**Comment by tianzhuo112** [comment]
同学，此处必有蹊跷啊！！！
<img width="623" alt="screen shot 2016-08-05 at 9 30 47 pm" src="https://cloud.githubusercontent.com/assets/17450179/17438528/dddd1f00-5b55-11e6-965b-34e398bb55bd.png">
<img width="623" alt="screen shot 2016-08-05 at 9 31 02 pm" src="https://cloud.githubusercontent.com/assets/17450179/17438529/dde1c3ca-5b55-11e6-89b3-69bc2931e009.png">

**Comment by junwangInChina** [comment]
的确不行

**Comment by henshao** [comment]
我们也在Swift中使用VTMagic，目前工作的很好。
在桥接文件中不包含VTMagic的头文件，在Swift代码import试试看。
理论上，桥接文件包含和Swift里面import两种方式都是可以的。

**Comment by junwangInChina** [comment]
谢谢，神奇的bug，又可用用了。
