### ISSUE TITLE
作者辛苦了,不过有没有item在导航栏下面的那种呢?

### ISSUE THREAD

**Issue by xiaoyao20084321** [tianzhuo112/VTMagic#3]
发现item都是在导航栏上.有没有在导航栏下面那种.

**Comment by tianzhuo112** [comment]
你好，你说的item在导航栏下面，是指在系统导航栏（UINavigationBar）下面？如果是这种情况，你可以在demo工程中的尝试加上这么一句话[self.navigationController setNavigationBarHidden:NO];看看这是不是你想要的效果，然后再调试一下（比如你可能需要把self.magicView.againstStatusBar设为NO）。最后，VTMagic的导航栏是内部自定义的，并非系统导航栏。

**Comment by xiaoyao20084321** [comment]
这样啊,谢谢啦,我去试试

**Comment by jarrydfillmore** [comment]
+1!

**Comment by iShawnWang** [comment]
正在尝试将 magicView.navigationView 设置为 self.navigationItem.titleView 把它加到系统的导航栏中 ~ 💯

**Comment by iShawnWang** [comment]
还是改成这样了 ~
`    [self.navigationController.navigationBar insertSubview:_pagerController.magicView.navigationView atIndex:1];
    _pagerController.magicView.navigationView.center = self.navigationController.navigationBar.center;`
