### ISSUE TITLE
UIColor+Magic.h VTColorZero编译问题

### ISSUE THREAD

**Issue by henshao** [tianzhuo112/VTMagic#30]
我们项目封装了一个UIKit组件，这个组件依赖VTMagic，这样使用会报编译错误。目前还不知道具体原因。

我发现VTColorZero只有一个地方在用，是否可以将`static const VTColor VTColorZero;`这句代码移动到VTColorIsZero函数里面呢？如下所示。

```
CG_INLINE BOOL
VTColorIsZero(VTColor aColor)
{
    static const VTColor VTColorZero;
    return VTColorIsEqual(VTColorZero, aColor);
}
```

![snip20160809_6](https://cloud.githubusercontent.com/assets/378953/17511248/ae64d66c-5e54-11e6-8f96-21dc3d4ab524.png)
![snip20160809_7](https://cloud.githubusercontent.com/assets/378953/17511249/aea621da-5e54-11e6-9721-cdbef115b9c4.png)

**Comment by henshao** [comment]
我们现在主要使用Swift开发。以前只有主工程依赖VTMagic，使用也是没有问题的，后来拆出来的UIKit也依赖VTMagic，这样主工程和UIKit都依赖VTMagic，然后就会报错。

**Comment by tianzhuo112** [comment]
你好，如果确定没问题，你可以先这样处理！

**Comment by henshao** [comment]
我这样修改之后，pod install一下就没了，另外所有的人也要做同样的修改，所以能否发一个小版本做这个修改呢？😄

**Comment by tianzhuo112** [comment]
唔，1.2.4的开发基本已经结束，我会尽快在明天更新一下版本。

**Comment by henshao** [comment]
好的呢，辛苦啦👍

**Comment by henshao** [comment]
头文件应该只放变量声明和函数声明吧，为什么在这个头文件里面声明并定义了VTColorZero变量，并且实现了很多函数？VTColorZero是不是通过extern在.h里面声明，而将定义放到.m里面会更好？VTColorMake这些函数也可以这里处理。

**Comment by tianzhuo112** [comment]
VTColor的处理参考了系统中CGRectMake的处理方式，请将podfile改为如下再试试：
```objective-c
pod 'VTMagic', :git => 'https://github.com/tianzhuo112/VTMagic.git'
```

**Comment by henshao** [comment]
我验证过啦，没问题了。

另外，CoreGraphics里面CGGeometry.h确实是这样定义函数的，不过头文件里面加了宏避免多次包含。

```
#ifndef CGGEOMETRY_H_
#define CGGEOMETRY_H_
#endif
```

**Comment by henshao** [comment]
亲，下一个版本什么时候发布呢？

**Comment by tianzhuo112** [comment]
你好，不出意外的话1.2.4会在今晚发布。

**Comment by henshao** [comment]
棒！

**Comment by tianzhuo112** [comment]
你好，1.2.4已发布，该版包含这个修复，请更新！
