### ISSUE TITLE
滑动的时候pageIndex不准确

### ISSUE THREAD

**Issue by qqcc1388** [tianzhuo112/VTMagic#31]
- (UIViewController *)magicView:(VTMagicView *)magicView viewControllerAtPage:(NSUInteger)pageIndex {
    NSLog(@"Index = %zi",pageIndex);
    static NSString *gridId = @"grid.identifier";
    VTGridViewController *viewController = [magicView dequeueReusablePageWithIdentifier:gridId];
    if (!viewController) {
        viewController = [[VTGridViewController alloc] init];
    }
    viewController.menuInfo = menuInfo;
    return viewController;
}

当在ScrollView中来回多滑动几次的时候，你会发现PageIndex的值就不准了，望修复这个bug，谢谢！

**Comment by tianzhuo112** [comment]
你好，这个pageIndex是需要加载的页面对应的页面索引，并非当前的页面索引，self.currentPage才是当前页面索引。

**Comment by qqcc1388** [comment]
好的明白了， 谢谢！
