### ISSUE TITLE
手势冲突

### ISSUE THREAD

**Issue by lipengda** [tianzhuo112/VTMagic#32]
VTMagic滑动切换controller和tableview中cell左滑删除有冲突应该如何处理

**Comment by tianzhuo112** [comment]
你好，这个问题你可以把scrollEnabled置为NO临时处理下，先禁止左右滑动切换，这两天我研究下手势冲突的问题。

**Comment by lipengda** [comment]
明白!感谢!

**Comment by DaokunBai** [comment]
我也遇到这个问题了，目前做法是magicView的scrollEnabled设置为NO，然后给tableView添加pan手势，当pan手势在cell上时不响应，在其他区域时响应pan手势

**Comment by GMlc** [comment]
设置手势的代理，然后在这个方法
- gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:中判断位置决定是否同时启用滑动和手势。
