### ISSUE TITLE
您好，怎么在item上面添加badgeNumber

### ISSUE THREAD

**Issue by junjie521123** [tianzhuo112/VTMagic#4]
如果要实现这个功能怎么扩展一下。

**Comment by tianzhuo112** [comment]
你好，item支持自定义，你只需要自定义一个集成自UIButton的类，再修改magicView:menuItemAtIndex:中的实现即可。

**Comment by junjie521123** [comment]
好的，我弄好了。 还有一个问题就是contentViews比较多的时候，我看源代码是进行了重用，但是比如我的contentView是tableView ，我把第一个contentview 上下滑动到界面的中部，当我左右滑动viewController的时候当第n个contentView重用了第一个contentView的时候 它默认显示也是在中部，我想要它在最开始的地方，这个功能怎么实现。

**Comment by tianzhuo112** [comment]
你好，这种情况你需要重写vtm_prepareForReuse，该方法会在页面被重用时调用，你可以在这个方法里面修正页面位置，或者清除页面数据。非常抱歉现在才回复！［尴尬脸］
