### ISSUE TITLE
怎么修改显示导航后的VTMagicView的红色背景

### ISSUE THREAD

**Issue by emptywalker** [tianzhuo112/VTMagic#40]
如果所示，我想修改这个红色背景，因为它会影响导航的背景效果，
要在哪里修改这个颜色

![image](https://cloud.githubusercontent.com/assets/12522809/18861942/4f3c31de-84bb-11e6-92c8-d608df4df524.png)

**Comment by tianzhuo112** [comment]
你好，红色部分应该是headerView。

**Comment by emptywalker** [comment]
@tianzhuo112   thanks
