### ISSUE TITLE
默认的tab文字颜色可以设置吗？没找到属性

### ISSUE THREAD

**Issue by Jasonvvei** [tianzhuo112/VTMagic#42]
如下图标示的颜色可以改吗？
![138748e0-5533-4a74-a499-9ddfe9569b09](https://cloud.githubusercontent.com/assets/14148888/18943105/f5fc1a58-864f-11e6-857d-0bd53f043831.png)

**Comment by tianzhuo112** [comment]
如下所示，修改menuItem的文本颜色和字体即可。
<img width="657" alt="screen shot 2016-09-29 at 2 36 55 pm" src="https://cloud.githubusercontent.com/assets/17450179/18943481/77ae5442-8652-11e6-810f-003254c2adb8.png">

**Comment by Jasonvvei** [comment]
好吧  这个知道啊，还是感谢
