### ISSUE TITLE
隐藏菜单

### ISSUE THREAD

**Issue by Wu-Dong-Hui** [tianzhuo112/VTMagic#43]
请教一下，如果想完全隐藏菜单栏（如图，红色框），如何做？谢谢
![123](https://cloud.githubusercontent.com/assets/8233494/18949312/5f63c50a-866d-11e6-95bf-dc0dda75258b.png)

**Comment by tianzhuo112** [comment]
呃，我有点好奇为啥需要隐藏菜单栏，不过你可以尝试把navigationHeight设为0来达到类似效果；而如果你是直接实例化的VTMagicController的话，你甚至可以修改VTMagicView的约束来达到同样的效果。

**Comment by Wu-Dong-Hui** [comment]
有个需求：展示某物详情，左右滑动查看前后某物详情
谢谢，你的建议
