### ISSUE TITLE
你好，请问未选中文字颜色和已选中文字颜色的属性能开放出来吗？

### ISSUE THREAD

**Issue by cijianzy** [tianzhuo112/VTMagic#47]
因为有这种多元化的视觉需求，请问能支持么？

**Comment by tianzhuo112** [comment]
你好，你只需要设置menuItem的选中和未选中状态的颜色即可。
<img width="657" alt="screen shot 2016-10-26 at 10 38 05 pm" src="https://cloud.githubusercontent.com/assets/17450179/19730480/f4b818da-9bcc-11e6-9ce9-3872c076b3bc.png">

**Comment by cijianzy** [comment]
好的 非常感谢！
