### ISSUE TITLE
参考demo，滚动的时候缓存数据

### ISSUE THREAD

**Issue by EasonGaoDevelop** [tianzhuo112/VTMagic#49]
在disappear 里面保存，在setMenuinfo 里面去读取本地数据，顺带判断时间是否满足一小时，调试发现，当我有五个栏目的时候，左右滑动，只能保存一次数据。在save 和load 本地数据的时候，menuID 并不是当前展示的ID

**Comment by tianzhuo112** [comment]
你好，这个问题我应该已经在QQ上有过回复。
