### ISSUE TITLE
导航栏效果可以加上网易那种放大效果

### ISSUE THREAD

**Issue by 977616908** [tianzhuo112/VTMagic#5]
导航栏效果可以加上网易那种放大效果吗？

**Comment by tianzhuo112** [comment]
你好，该功能最近正在完善，效果优化中，或许要不了多久大家就能看到。

**Comment by tianzhuo112** [comment]
你好，1.2.1已新增放大效果，只需设置合适的itemScale即可，参见demo中的Home模块，如有问题欢迎及时反馈！
