### ISSUE TITLE
请问如何改变选中字体的颜色或者大小

### ISSUE THREAD

**Issue by jianjianhao** [tianzhuo112/VTMagic#52]
好像没看到有相关的API

**Comment by tianzhuo112** [comment]
你好，这个问题在closed中可以找到，修改menuItem的normal和selected状态的字体颜色即可。

**Comment by 1knight520** [comment]
> 你好，这个问题在关闭中可以找到，修改菜单项的正常和选定状态的字体颜色。

你好 怎么修改选中字体大小呢 没在closed种看到啊
