### ISSUE TITLE
VTMagicController中的currentPage方法不准确

### ISSUE THREAD

**Issue by WJLollipop** [tianzhuo112/VTMagic#70]
我在VTMagicController容器中放了3个menuItem，根据需求要判断当前页是第几页。
子控制器中代码如下：
VTMagicController *vc = (VTMagicController *)weakSelf.magicController;
NSInteger Index =  [vc currentPage];
当滚动到第3个页面时，实际返回的index是0，应该返回2
当menuItem为4个时，Index返回的又是对的

**Comment by Suzhibin** [comment]
viewDidAppear 里写
 NSInteger pageIndex = [self vtm_pageIndex];
