### ISSUE TITLE
当menuItem超过一屏的情况下，列表在左右快速切换时，第二屏的menuItem一开始不会随着切换显示，只有滚动结束时才会切换到第二屏的menuItem

### ISSUE THREAD

**Issue by WJLollipop** [tianzhuo112/VTMagic#75]
现在是在 scrollViewDidEndDecelerating方法中，调用updateMenuBarWhenSwitchEnd方法，能否在scrollViewDidScroll中调用该方法？

**Comment by Suzhibin** [comment]
@WJLollipop   self.magicView.switchStyle= VTSwitchStyleStiff; 设置这个枚举 就可以实现你要的效果。
